shapes: v2: add SHACL shapes for new RML ontology
kg-construct/rml-star pull request #16
Opened 2023-03-30 10:04 UTC by DylanVanAssche

These shapes covers the RML-Star specification:

- rmls:NonAssertedTriplesMap
- rmls:StarMap

The generate_shapes.py script combines these shapes into a single shape for SHACL validators 'star.ttl'

2023-03-30 10:07 UTC, DylanVanAssche commented
The `sh:description` entries need work, please provide some feedback what they should be

2023-04-18 13:15 UTC, anaigmo requested changes
They look great :) I've made some comments regarding some descriptions and for changing the IRIs.

I'm missing some restrictions regarding the range of the core properties `rml:subjectMap` and `rml:objectMap` (`rml:StarMap`). In the core, we strip all references to this module, so I think they would be put here instead if there is a way that they not enter in conflict with the core ones

2023-04-18 13:15 UTC, anaigmo commented on shapes/v2/nonassertedtriples_map.ttl
> +@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
update to:
```
@prefix rml: <http://w3id.org/rml/> .
```
the `rmls` prefix is not needed

2023-04-18 13:15 UTC, anaigmo commented on shapes/v2/nonassertedtriples_map.ttl
> +@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
the `rmls` prefix applies to the entire document, it'd need to be replaced with `rml`

2023-04-18 13:15 UTC, anaigmo commented on shapes/v2/nonassertedtriples_map.ttl
> +    one rml:subjectMap and zero or more rml:predicateObjectMaps.
...and exactly one logical source (according also to the restrictions below)

2023-04-18 13:15 UTC, anaigmo commented on shapes/v2/star.ttl
> +    or more rml:predicateObjectMaps
This desc is for the NonAssertedTriplesMap, please replace with "rml:StarMap requires exactly one rml:quotedTriplesMap and zero or more rml:joinCondition."

2023-04-18 13:15 UTC, anaigmo commented on shapes/v2/star.ttl
> +        the parent logical table of the foreign key constraint.
Please replace with the new description of join condition: "Specifies the join condition for joining the child logical source with the parent logical source of the foreign key constraint."

2023-04-18 13:15 UTC, anaigmo commented on shapes/v2/star.ttl
> +            sh:path rml:joinCondition ;
I see cardinality restrictions for `child` and `parent`, but not for joinCondition, which would be the same as for the core spec (0..N I think)

Also, the core spec has added `childMap` and `parentMap`, according to [#59](https://github.com/kg-construct/rml-core/issues/59), which may be need to be reflected here

2023-04-18 13:15 UTC, anaigmo commented on shapes/v2/star_map.ttl
> +    or more rml:predicateObjectMaps
same comment as in the star.ttl file regarding the desc of the starmap

2023-04-28 07:17 UTC, DylanVanAssche commented
@anaigmo We reworked the shapes in Core to have inheritance for things like `joinCondition`, etc. which are shared among multiple resources. Once merged in Core, I can update them here to match.

2023-04-28 14:30 UTC, merged